# Generated by Django 2.0.3 on 2018-09-07 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notas', '0042_auto_20180907_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('contato', models.CharField(max_length=30)),
                ('telefone', models.CharField(blank=True, max_length=17)),
                ('telefone2', models.CharField(blank=True, max_length=17)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('descricao', models.CharField(blank=True, max_length=150)),
                ('imagem', models.FileField(blank=True, upload_to='empresas_servicos')),
            ],
        ),
        migrations.CreateModel(
            name='ServicoTerceirizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True)),
                ('descricao', models.CharField(max_length=150)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('imagem', models.FileField(blank=True, upload_to='servicos_terceirizados')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicos_terceirizados.EmpresaServico')),
                ('projeto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notas.Projeto')),
            ],
        ),
    ]
