# Generated by Django 2.0.3 on 2018-09-07 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos_terceirizados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicoterceirizado',
            name='projeto',
        ),
    ]
