# Generated by Django 2.0.3 on 2018-09-07 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0044_auto_20180907_1502'),
        ('servicos_terceirizados', '0002_remove_servicoterceirizado_projeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicoterceirizado',
            name='empresa',
        ),
        migrations.DeleteModel(
            name='EmpresaServico',
        ),
        migrations.DeleteModel(
            name='ServicoTerceirizado',
        ),
    ]
