# Generated by Django 2.0.3 on 2018-09-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicos_terceirizados', '0003_auto_20180907_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoTerceirizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True)),
                ('descricao', models.CharField(max_length=150)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('imagem', models.FileField(blank=True, upload_to='servicos_terceirizados')),
            ],
        ),
    ]
