# Generated by Django 2.0.3 on 2018-09-09 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0053_auto_20180908_2129'),
        ('servicos_terceirizados', '0004_servicoterceirizado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicoTerceirizado',
        ),
    ]
