# Generated by Django 2.0.3 on 2018-09-11 02:20

from django.db import migrations, models
import django.db.models.deletion
import notas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comentarios', models.CharField(blank=True, help_text='Informações relacionadas com o depósito(opcional).', max_length=70)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('contato', models.CharField(max_length=30)),
                ('telefone', models.CharField(blank=True, max_length=17)),
                ('telefone2', models.CharField(blank=True, max_length=17)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('descricao', models.CharField(blank=True, max_length=150)),
                ('imagem', models.FileField(blank=True, upload_to='empresas_servicos')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('data', models.DateField(blank=True)),
                ('emitente', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=70)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('tipo_gasto', models.CharField(choices=[('Materiais', 'MATERIAIS'), ('Equipamentos', 'EQUIPAMENTOS'), ('Serviços', 'SERVIÇOS'), ('Funcionários', 'FUNCIONARIOS')], max_length=12)),
                ('imagem', models.FileField(blank=True, upload_to='notas_compras')),
                ('imagem1', models.FileField(blank=True, upload_to='notas_compras')),
                ('deposito', models.ForeignKey(default=notas.models.Nota.deposito_corrente, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notas.Deposito')),
            ],
            options={
                'ordering': ['data'],
                'permissions': (('can_change', 'Pode alterar notas'),),
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ServicoTerceirizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True)),
                ('descricao', models.CharField(max_length=150)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('imagem', models.FileField(blank=True, upload_to='servicos_terceirizados')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notas.EmpresaServico')),
                ('projeto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notas.Projeto')),
            ],
        ),
        migrations.AddField(
            model_name='nota',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notas.Projeto'),
        ),
        migrations.AddField(
            model_name='deposito',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notas.Projeto'),
        ),
    ]
