# Generated by Django 2.0.3 on 2018-09-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_nota_servico_terceirizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='tipo_gasto',
            field=models.CharField(choices=[('Materiais', 'MATERIAIS'), ('Equipamentos', 'EQUIPAMENTOS'), ('Serviços', 'SERVIÇOS'), ('Funcionários', 'FUNCIONARIOS'), ('Serviços Terceirizados', 'SERVIÇOS TERCEIRIZADOS')], max_length=12),
        ),
    ]
