# Generated by Django 2.0.3 on 2018-09-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0004_auto_20180914_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='tipo_gasto',
            field=models.CharField(choices=[('Depósitos', 'DEPOSITOS'), ('Equipamentos', 'EQUIPAMENTOS'), ('Funcionários', 'FUNCIONARIOS'), ('Impostos', 'IMPOSTOS'), ('Materiais', 'MATERIAIS'), ('Serviços', 'SERVIÇOS'), ('Serviços Terceirizados', 'SERVIÇOS TERCEIRIZADOS')], max_length=23),
        ),
    ]
