# Generated by Django 2.0.3 on 2018-04-14 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import notas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comentarios', models.CharField(blank=True, help_text='Informações relacionadas com o depósito(opcional).', max_length=70)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('data', models.DateField(blank=True)),
                ('emitente', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=70)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('tipo_gasto', models.CharField(choices=[('Serviços', 'SERVIÇOS'), ('Ferramentas', 'FERRAMENTAS')], max_length=12)),
                ('imagem', models.FileField(blank=True, upload_to='notas_compras')),
                ('imagem1', models.FileField(blank=True, upload_to='notas_compras')),
                ('deposito', models.ForeignKey(default=notas.models.Nota.deposito_corrente, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notas.Deposito')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=150)),
                ('alias', models.CharField(max_length=30)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
