# Generated by Django 2.0.3 on 2018-04-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0004_auto_20180418_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='tipo_gasto',
            field=models.CharField(choices=[('Materiais', 'MATERIAIS'), ('Equipamentos', 'EQUIPAMENTOS'), ('Serviços', 'SERVIÇOS'), ('Funcionários', 'FUNCIONARIOS')], max_length=12),
        ),
    ]
