# Generated by Django 2.0.3 on 2018-04-14 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquery',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserQuery',
        ),
    ]
