# Generated by Django 2.0.3 on 2018-04-18 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notas', '0002_auto_20180414_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=150)),
                ('alias', models.CharField(max_length=30)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='nota',
            name='tipo_gasto',
            field=models.CharField(choices=[('Materiais', 'MATERIAIS'), ('Equipamentos', 'EQUIPAMENTOS'), ('Serviços', 'SERVIÇOS')], max_length=12),
        ),
    ]
