# Generated by Django 2.0.3 on 2018-09-15 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notas', '0004_auto_20180914_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faturado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vencimento', models.DateField()),
                ('descricao', models.CharField(blank=True, max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('projeto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notas.Projeto')),
            ],
            options={
                'ordering': ['-vencimento'],
            },
        ),
    ]
