# Generated by Django 2.0.3 on 2018-09-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturado',
            name='pago',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
