# Generated by Django 2.0.3 on 2018-09-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturados', '0002_faturado_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturado',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
