# Generated by Django 2.0.3 on 2018-04-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0008_auto_20180409_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposito',
            name='comentarios',
            field=models.CharField(help_text='Informações relacionadas com o depósito(opcional).', max_length=70, null=True),
        ),
    ]
