# Generated by Django 2.0.3 on 2018-04-10 17:15

from django.db import migrations, models
import django.db.models.deletion
import notas.models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0010_auto_20180409_1826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposito',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='nota',
            name='emitente',
            field=models.CharField(default='nao informado', max_length=30),
        ),
        migrations.AlterField(
            model_name='deposito',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='nota',
            name='deposito',
            field=models.ForeignKey(default=notas.models.Nota.deposito_corrente, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notas.Deposito'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
