# Generated by Django 2.0.3 on 2018-04-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0011_auto_20180410_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='emitente',
            field=models.CharField(max_length=30),
        ),
    ]
