# Generated by Django 2.0.3 on 2018-04-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0012_auto_20180410_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='tipo_gasto',
            field=models.CharField(choices=[('Materiais', 'MATERIAIS'), ('Equipamentos', 'EQUIPAMENTOS'), ('Serviços', 'SERVIÇOS')], max_length=12),
        ),
    ]
