# Generated by Django 2.0.3 on 2018-04-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0014_auto_20180418_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nota',
            options={'permissions': (('can_change', 'Pode alterar notas'),)},
        ),
        migrations.AlterField(
            model_name='nota',
            name='tipo_gasto',
            field=models.CharField(choices=[('Materiais', 'MATERIAIS'), ('Equipamentos', 'EQUIPAMENTOS'), ('Serviços', 'SERVIÇOS'), ('Funcionários', 'FUNCIONARIOS')], max_length=12),
        ),
    ]
