# Generated by Django 2.0.3 on 2018-04-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0015_auto_20180419_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='projeto',
            field=models.CharField(choices=[('Marina', 'MARINA'), ('Casa_de_Eventos', 'CASA DE EVENTOS')], default='Marina', max_length=20),
        ),
    ]
