# Generated by Django 2.0.3 on 2018-04-19 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0016_nota_projeto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ['-data'], 'permissions': (('can_change', 'Pode alterar notas'),)},
        ),
    ]
