# Generated by Django 2.0.3 on 2018-04-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0018_auto_20180420_0357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(choices=[('Marina', 'MARINA'), ('Casa_de_Eventos', 'CASA DE EVENTOS')], default='Marina', max_length=30)),
            ],
        ),
    ]
