# Generated by Django 2.0.3 on 2018-04-20 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0019_projeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquery',
            name='user',
        ),
        migrations.AddField(
            model_name='deposito',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notas.Projeto'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nome_projeto',
            field=models.CharField(choices=[('Marina', 'MARINA'), ('CasaDeEventos', 'CASA DE EVENTOS')], default='Marina', max_length=30),
        ),
        migrations.DeleteModel(
            name='UserQuery',
        ),
    ]
