# Generated by Django 2.0.3 on 2018-04-20 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0021_auto_20180420_0438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='nome_projeto',
            new_name='nome',
        ),
    ]
