# Generated by Django 2.0.3 on 2018-04-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0024_auto_20180420_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='nome',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
