# Generated by Django 2.0.3 on 2018-04-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0027_auto_20180420_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default='', max_digits=10),
        ),
    ]
