# Generated by Django 2.0.3 on 2018-04-20 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0028_auto_20180420_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='projeto',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notas.Projeto'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
