# Generated by Django 2.0.3 on 2018-04-25 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0032_auto_20180420_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoTerceirizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True)),
                ('empresa', models.CharField(max_length=30)),
                ('contato', models.CharField(max_length=30)),
                ('telefone', models.CharField(blank=True, max_length=17)),
                ('descricao', models.CharField(max_length=150)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('imagem', models.FileField(blank=True, upload_to='servicos_terceirizados')),
                ('projeto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notas.Projeto')),
            ],
        ),
    ]
