# Generated by Django 2.0.3 on 2018-04-25 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0033_servicoterceirizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('contato', models.CharField(max_length=30)),
                ('telefone', models.CharField(blank=True, max_length=17)),
                ('telefone2', models.CharField(blank=True, max_length=17)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('descricao', models.CharField(max_length=150)),
                ('imagem', models.FileField(blank=True, upload_to='empresas_servicos')),
            ],
        ),
        migrations.RemoveField(
            model_name='servicoterceirizado',
            name='contato',
        ),
        migrations.RemoveField(
            model_name='servicoterceirizado',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='servicoterceirizado',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notas.EmpresaServico'),
        ),
    ]
