# Generated by Django 2.0.3 on 2018-09-07 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0041_auto_20180906_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicoterceirizado',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='servicoterceirizado',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='servico_terceirizado',
        ),
        migrations.DeleteModel(
            name='EmpresaServico',
        ),
        migrations.DeleteModel(
            name='ServicoTerceirizado',
        ),
    ]
