# Generated by Django 2.0.3 on 2018-09-07 18:08

from django.db import migrations, models
import django.db.models.deletion
import notas.models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0044_auto_20180907_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='servico_terceirizado',
            field=models.ForeignKey(default=notas.models.Nota.deposito_corrente, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notas.ServicoTerceirizado'),
        ),
    ]
