# Generated by Django 2.0.3 on 2018-09-08 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0045_nota_servico_terceirizado'),
        ('notas', '0046_auto_20180907_1509'),
    ]

    operations = [
    ]
