# Generated by Django 2.0.3 on 2018-09-08 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0047_merge_20180908_2017'),
        ('notas', '0048_auto_20180908_2019'),
    ]

    operations = [
    ]
