# Generated by Django 2.0.3 on 2018-09-08 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0050_auto_20180908_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='servico_terceirizado',
        ),
    ]
