# Generated by Django 2.0.3 on 2018-09-08 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos_terceirizados', '0004_servicoterceirizado'),
        ('notas', '0051_remove_nota_servico_terceirizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='servico_terceirizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicos_terceirizados.ServicoTerceirizado'),
        ),
    ]
